#!/usr/bin/env node
// researcher.mjs — Real research executor for aeon-researcher.
//
// Reads recent git history, scans relevant files, creates structured
// research issues on the GitLawb repo via `gl issue create`.
//
// Env vars (set by task-runner):
//   GITLAWB_TASK_JSON   — full task object
//   GITLAWB_AGENT_JSON  — agent instance object
//   GITLAWB_REPO_DIR    — repo working directory

import { spawnSync } from "node:child_process";
import { readFileSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";

const repoDir = process.env.GITLAWB_REPO_DIR || ".";
const task = JSON.parse(process.env.GITLAWB_TASK_JSON || "{}");
const agent = JSON.parse(process.env.GITLAWB_AGENT_JSON || "{}");

const payload = typeof task.payload === "string" ? JSON.parse(task.payload) : (task.payload || {});
const topic = payload.topic || payload.title || payload.prompt || task.kind || "fleet activity";
const scope = payload.scope || "";

function run(cmd, args, opts = {}) {
  const proc = spawnSync(cmd, args, { cwd: repoDir, encoding: "utf8", ...opts });
  return proc.stdout?.trim() || "";
}

// Gather recent activity
const recentCommits = run("git", ["log", "--oneline", "-20", "--since=3 days ago"]);
const recentFiles = run("git", ["diff", "--name-only", "HEAD~10..HEAD"]);
const fileCount = recentCommits.split("\n").filter(Boolean).length;

// Scan files in scope. The task generator sets `scope` to a comma-separated
// list of changed files, but it may also be a single dir/file path — handle
// both. For a directory, find source files under it; for a file, take it
// directly. (Previously the whole comma-joined string was treated as one path,
// which never exists for multi-file commits, so scanning was silently skipped.)
let scannedFiles = [];
if (scope) {
  for (const rel of scope.split(/[,\n]/).map(s => s.trim()).filter(Boolean)) {
    const full = join(repoDir, rel);
    if (!existsSync(full)) continue;
    if (statSync(full).isDirectory()) {
      // Run from repoDir so results stay repo-relative (the reader below joins
      // each entry back onto repoDir).
      const proc = spawnSync("find", [rel, "-type", "f", "(", "-name", "*.mjs", "-o", "-name", "*.js", "-o", "-name", "*.yml", "-o", "-name", "*.md", ")"], { cwd: repoDir, encoding: "utf8" });
      scannedFiles.push(...(proc.stdout || "").split("\n").filter(Boolean));
    } else {
      scannedFiles.push(rel);
    }
    if (scannedFiles.length >= 10) break;
  }
  scannedFiles = scannedFiles.slice(0, 10);
}

// Read scanned files for content analysis
const fileInsights = [];
for (const f of scannedFiles.slice(0, 5)) {
  try {
    const content = readFileSync(join(repoDir, f), "utf8");
    const lines = content.split("\n").length;
    const exports = content.match(/export\s+(class|function|const)\s+(\w+)/g) || [];
    const imports = content.match(/import\s+.*from\s+["']([^"']+)["']/g) || [];
    fileInsights.push({
      file: f.replace(repoDir + "/", ""),
      lines,
      exports: exports.map(e => e.replace(/export\s+(class|function|const)\s+/, "")),
      imports: imports.length,
    });
  } catch {}
}

// Check existing issues to avoid duplicates
const existingIssues = run("gl", ["issue", "list", "aeon", "--limit", "10"]);
const recentIssueTitles = existingIssues.split("\n").filter(Boolean).map(l => l.toLowerCase());

// Build research report
const today = new Date().toISOString().slice(0, 10);
const reportTitle = `Research: ${topic} (${today})`;

// Skip if we already researched this today
if (recentIssueTitles.some(t => t.includes(topic.toLowerCase()) && t.includes(today))) {
  console.log(`Already researched "${topic}" today, skipping`);
  process.exit(0);
}

const body = [
  `## Research Report: ${topic}`,
  ``,
  `**Date:** ${today}`,
  `**Agent:** ${agent.name} (${agent.did})`,
  `**Scope:** ${scope || "full repo"}`,
  `**Task:** ${task.id}`,
  ``,
  `### Recent Activity (${fileCount} commits in last 3 days)`,
  `\`\`\``,
  recentCommits || "(no recent commits)",
  `\`\`\``,
  ``,
  `### Changed Files`,
  `\`\`\``,
  recentFiles || "(no recent changes)",
  `\`\`\``,
];

if (fileInsights.length > 0) {
  body.push(`### File Analysis`);
  for (const fi of fileInsights) {
    body.push(`- **${fi.file}** — ${fi.lines} lines, exports: [${fi.exports.join(", ")}], ${fi.imports} module imports`);
  }
  body.push("");
}

body.push(`### Key Observations`);
if (fileCount === 0) {
  body.push("- No recent commits — repository may be in a stable state or inactive");
} else {
  body.push(`- ${fileCount} commits in the last 3 days indicates ${fileCount > 10 ? "active" : "moderate"} development`);
}

if (fileInsights.some(f => f.exports.length > 3)) {
  body.push("- Multiple exported interfaces detected — potential for API surface growth");
}

body.push("");
body.push(`*Generated by aeon-researcher via GitLawb task runner*`);

// Create the issue
const result = spawnSync("gl", [
  "issue", "create",
  "--title", reportTitle,
  "--body", body.join("\n"),
  "aeon",
], { cwd: repoDir, encoding: "utf8" });

if (result.status !== 0) {
  const err = result.stderr || result.stdout || "unknown error";
  console.error(`Failed to create issue: ${err}`);
  process.exit(1);
}

const issueUrl = (result.stdout || "").trim();
console.log(`Research complete: "${reportTitle}" — ${fileCount} commits analyzed, ${fileInsights.length} files scanned. Issue: ${issueUrl}`);
