#!/usr/bin/env python3
"""Generate docs/skill-graph.md from .skill_graph_data.json."""
import json
import os
import hashlib
import sys
from collections import defaultdict

ROOT = "/home/runner/work/aeon/aeon"
os.chdir(ROOT)

with open(".skill_graph_data.json") as fh:
    D = json.load(fh)

TODAY = D["today"]
MODE = D["mode"]
FP = D["input_fingerprint"]

CAT_LABELS = {
    "research": "Research & Content",
    "dev": "Dev & Code",
    "crypto": "Crypto & Markets",
    "social": "Social",
    "productivity": "Productivity & Meta",
    "other": "Other & Uncategorized",
}
CAT_ORDER = ["research", "dev", "crypto", "social", "productivity", "other"]

skills = D["skills"]
by_slug = {s["slug"]: s for s in skills}
by_cat = defaultdict(list)
for s in skills:
    by_cat[s["category"]].append(s["slug"])
for c in by_cat:
    by_cat[c].sort()

total = len(skills)
enabled_count = sum(1 for s in skills if s["enabled"])

# Edge lists
dep = D["edges_depends_on"]
consume = D["edges_consume"]
reactive = D["edges_reactive"]
shared = D["edges_shared_state"]
content = D["edges_content_pipeline"]

# --- Lint (basic) ---
lint_errors = []
all_slugs = set(by_slug.keys())
for e in dep + shared + content:
    if e["from"] not in all_slugs:
        lint_errors.append(f"unknown from-node: {e['from']}")
    if e["to"] not in all_slugs:
        lint_errors.append(f"unknown to-node: {e['to']}")
for skill_dir in os.listdir("skills"):
    if not os.path.isdir(f"skills/{skill_dir}"):
        continue
if lint_errors:
    print("LINT_FAIL:", lint_errors, file=sys.stderr)
    sys.exit(2)

# --- Verdict line ---
verdict = f"SKILL_GRAPH_NEW — {total} skills mapped across {len(CAT_ORDER)} categories, {enabled_count} enabled"

# --- Build output ---
out = []
out.append("# Skill Dependency Graph\n\n")
out.append(f"> Auto-generated by `skill-graph` on {TODAY}. Mode: `{MODE}`.\n\n")
out.append(f"**Verdict:** {verdict}\n\n")

# --- Overview diagram ---
out.append("## Overview\n\n")
out.append("Category boxes show **enabled / total** skill counts. Cross-category edges carry their count.\n\n")
out.append("```mermaid\n")
out.append("flowchart LR\n")
for cat in CAT_ORDER:
    slugs = by_cat.get(cat, [])
    en = sum(1 for s in slugs if by_slug[s]["enabled"])
    out.append(f'    subgraph {cat}["{CAT_LABELS[cat]} ({en} / {len(slugs)})"]\n')
    out.append(f'        {cat}_anchor( )\n')
    out.append('    end\n')

cross = defaultdict(int)
for e in dep + shared + content:
    fc = by_slug[e["from"]]["category"]
    tc = by_slug[e["to"]]["category"]
    if fc != tc:
        cross[(fc, tc)] += 1
for (fc, tc), n in sorted(cross.items()):
    out.append(f'    {fc}_anchor -->|"{n}"| {tc}_anchor\n')
for cat in CAT_ORDER:
    out.append(f'    style {cat}_anchor fill:transparent,stroke:transparent\n')
out.append("```\n\n")

out.append("_Every skill also writes `memory/cron-state.json`, which is read by `heartbeat`, `skill-health`, `skill-repair`, and `skill-evals`. Collapsed here to keep the map readable — see Self-healing loop below._\n\n")

# --- Self-healing loop ---
out.append("## Self-healing loop\n\n")
out.append("Reactive trigger: `skill-repair` fires on `consecutive_failures >= 3` for any skill; `planner` fires on `>= 2` to re-plan the day around the regressing area.\n\n")
out.append("""```mermaid
flowchart LR
    heartbeat[heartbeat]
    skill-health[skill-health]
    skill-evals[skill-evals]
    skill-repair[skill-repair]
    self-improve[self-improve]
    planner[planner]
    cron[("memory/cron-state.json")]
    heartbeat --> skill-health
    skill-health --> skill-evals
    skill-evals --> skill-repair
    skill-repair --> self-improve
    self-improve -.->|"updates aeon.yml"| heartbeat
    heartbeat -.-> cron
    skill-health -.-> cron
    skill-evals -.-> cron
    skill-repair -.-> cron
    cron -.->|"consecutive_failures >= 2"| planner
    cron -.->|"consecutive_failures >= 3"| skill-repair
    click heartbeat "../skills/heartbeat/SKILL.md"
    click skill-health "../skills/skill-health/SKILL.md"
    click skill-evals "../skills/skill-evals/SKILL.md"
    click skill-repair "../skills/skill-repair/SKILL.md"
    click self-improve "../skills/self-improve/SKILL.md"
    click planner "../skills/planner/SKILL.md"
```

""")

# --- Per-category diagrams ---
out.append("## Per-category breakdown\n\n")
cross_by_source_cat = defaultdict(list)
cross_by_target_cat = defaultdict(list)
for e in dep + shared + content:
    fc = by_slug[e["from"]]["category"]
    tc = by_slug[e["to"]]["category"]
    if fc != tc:
        cross_by_source_cat[fc].append(e)
        cross_by_target_cat[tc].append(e)

intra_dep = defaultdict(list)
intra_shared = defaultdict(list)
intra_content = defaultdict(list)
for e in dep:
    fc = by_slug[e["from"]]["category"]
    tc = by_slug[e["to"]]["category"]
    if fc == tc:
        intra_dep[fc].append(e)
for e in shared:
    fc = by_slug[e["from"]]["category"]
    tc = by_slug[e["to"]]["category"]
    if fc == tc:
        intra_shared[fc].append(e)
for e in content:
    fc = by_slug[e["from"]]["category"]
    tc = by_slug[e["to"]]["category"]
    if fc == tc:
        intra_content[fc].append(e)

for cat in CAT_ORDER:
    slugs = by_cat.get(cat, [])
    en = sum(1 for s in slugs if by_slug[s]["enabled"])
    out.append(f"### {CAT_LABELS[cat]} ({en} / {len(slugs)})\n\n")
    out.append("```mermaid\n")
    out.append("flowchart LR\n")
    out.append("    classDef enabled fill:#fff,stroke:#000,stroke-width:2px,color:#000\n")
    out.append("    classDef disabled fill:#f5f5f5,stroke:#bbb,color:#888\n")
    out.append("    classDef external fill:none,stroke:#bbb,stroke-dasharray:3 3,color:#888\n")
    for slug in slugs:
        s = by_slug[slug]
        if s["enabled"] and s["schedule"]:
            out.append(f'    {slug}["{slug}<br/><i>{s["schedule"]}</i>"]\n')
        else:
            out.append(f'    {slug}["{slug}"]\n')
    # Intra edges
    for e in intra_dep[cat]:
        out.append(f'    {e["from"]} --> {e["to"]}\n')
    for e in intra_shared[cat]:
        out.append(f'    {e["from"]} -..-> {e["to"]}\n')
    for e in intra_content[cat]:
        out.append(f'    {e["from"]} -..-> {e["to"]}\n')
    # External ghost nodes for cross-cat outgoing (source is here, target elsewhere)
    external_targets = {}
    for e in cross_by_source_cat[cat]:
        t = e["to"]
        tc = by_slug[t]["category"]
        external_targets[t] = tc
    # External ghost nodes for cross-cat incoming (source elsewhere, target here)
    external_sources = {}
    for e in cross_by_target_cat[cat]:
        f = e["from"]
        fc = by_slug[f]["category"]
        external_sources[f] = fc
    for t, tc in sorted(external_targets.items()):
        if t not in slugs:  # true external
            out.append(f'    {t}["{t}<br/><i>{tc}</i>"]\n')
    for f, fc in sorted(external_sources.items()):
        if f not in slugs and f not in external_targets:
            out.append(f'    {f}["{f}<br/><i>{fc}</i>"]\n')
    # cross edges (both directions), drawn between local skill and external node
    for e in cross_by_source_cat[cat] + cross_by_target_cat[cat]:
        # avoid duplicates
        pass
    seen_cross = set()
    for e in dep + shared + content:
        fc = by_slug[e["from"]]["category"]
        tc = by_slug[e["to"]]["category"]
        if fc == tc:
            continue
        if fc != cat and tc != cat:
            continue
        key = (e["from"], e["to"], "dep" if e in dep else ("content" if e in content else "shared"))
        if key in seen_cross:
            continue
        seen_cross.add(key)
        if e in dep:
            out.append(f'    {e["from"]} --> {e["to"]}\n')
        else:
            out.append(f'    {e["from"]} -..-> {e["to"]}\n')
    # Click-through for local + external
    for slug in slugs:
        out.append(f'    click {slug} "../skills/{slug}/SKILL.md"\n')
    printed_click = set(slugs)
    for t in sorted(external_targets):
        if t not in printed_click:
            out.append(f'    click {t} "../skills/{t}/SKILL.md"\n')
            printed_click.add(t)
    for f in sorted(external_sources):
        if f not in printed_click:
            out.append(f'    click {f} "../skills/{f}/SKILL.md"\n')
            printed_click.add(f)
    # Class assignments
    en_slugs = [s for s in slugs if by_slug[s]["enabled"]]
    dis_slugs = [s for s in slugs if not by_slug[s]["enabled"]]
    if en_slugs:
        out.append("    class " + ",".join(en_slugs) + " enabled\n")
    if dis_slugs:
        out.append("    class " + ",".join(dis_slugs) + " disabled\n")
    ext_all = sorted(set(list(external_targets) + list(external_sources)) - set(slugs))
    if ext_all:
        out.append("    class " + ",".join(ext_all) + " external\n")
    out.append("```\n\n")

# --- Legend ---
out.append("""## Legend

| Edge | Meaning |
|------|---------|
| `-->` solid | `depends_on` — declared in frontmatter |
| `-.->` dashed | `consume` — chain step receives prior output |
| `-..->` dotted | shared-state — one skill writes a memory file another reads, or a research/content skill feeds the distribution pipeline |

| Node style | Meaning |
|------------|---------|
| **Bold border** | Enabled in `aeon.yml` (schedule shown beneath) |
| Faded grey | Disabled / not scheduled |
| Dashed border | External skill referenced from another category |

Click any node on github.com to open its `SKILL.md`. Reactive triggers and the shared `memory/cron-state.json` ledger are documented in the **Self-healing loop** section, not duplicated as edges in the per-category diagrams.

""")

# --- Summary ---
out.append("## Summary\n\n")
out.append("| Category | Total | Enabled |\n")
out.append("|----------|-------|---------|\n")
grand_total = 0
grand_enabled = 0
for cat in CAT_ORDER:
    slugs = by_cat.get(cat, [])
    en = sum(1 for s in slugs if by_slug[s]["enabled"])
    out.append(f"| {CAT_LABELS[cat]} | {len(slugs)} | {en} |\n")
    grand_total += len(slugs)
    grand_enabled += en
out.append(f"| **Total** | **{grand_total}** | **{grand_enabled}** |\n\n")

out.append("| Edge type | Count |\n")
out.append("|-----------|-------|\n")
out.append(f"| `depends_on` | {len(dep)} |\n")
out.append(f"| `consume` (chains) | {len(consume)} |\n")
out.append(f"| `reactive` | {len(reactive)} |\n")
out.append(f"| `shared_state` (derived) | {len(shared)} |\n")
out.append(f"| `content_pipeline` (derived) | {len(content)} |\n\n")

out.append("---\n\n")
foot = (
    f"_skills parsed: {total} · depends_on: {len(dep)} · consume: {len(consume)} · "
    f"reactive: {len(reactive)} · shared-state derived: {len(shared)} · "
    f"content-pipeline derived: {len(content)} · enabled: {enabled_count}/{total} · "
    f"mode: {MODE}_\n"
)
out.append(foot)

# Write docs/skill-graph.md
with open("docs/skill-graph.md", "w") as fh:
    fh.write("".join(out))

# --- Persist state ---
sorted_slugs = sorted(by_slug.keys())
edge_tuples = sorted(
    [f"dep:{e['from']}->{e['to']}" for e in dep]
    + [f"con:{e['from']}->{e['to']}" for e in consume]
    + [f"rea:{e['from']}:{e['condition']}" for e in reactive]
    + [f"shs:{e['from']}->{e['to']}" for e in shared]
    + [f"con:{e['from']}->{e['to']}" for e in content]
)
node_sha = hashlib.sha1("\n".join(sorted_slugs).encode()).hexdigest()
edge_sha = hashlib.sha1("\n".join(edge_tuples).encode()).hexdigest()

state = {
    "generated_at": TODAY,
    "input_fingerprint": FP,
    "skills_total": total,
    "enabled_count": enabled_count,
    "edges": {
        "depends_on": len(dep),
        "consume": len(consume),
        "reactive": len(reactive),
        "shared_state": len(shared),
        "content_pipeline": len(content),
    },
    "node_list_sha": node_sha,
    "edge_list_sha": edge_sha,
    "mode": MODE,
    "verdict": verdict,
}
os.makedirs("memory/topics", exist_ok=True)
with open("memory/topics/skill-graph-state.json", "w") as fh:
    json.dump(state, fh, indent=2)
    fh.write("\n")

print("verdict:", verdict)
print("wrote: docs/skill-graph.md")
print("wrote: memory/topics/skill-graph-state.json")
